# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d1f8baa6c6e9cd718261df505cac388bf2df6f36ea570c9a1edcf0dc8eddd940927cf37fbeddeccc20ffd6d545968562d6bd515d7bee2eaf5a318f19f457f5

test:
  secret_key_base: ddde04a83fe79d3aeeb1ff83e59be067c9fb5c059969b26cfdc0a8133775fc2c43fe3b37becd27295415bf855f88ff869556bce099100093a4e1cbc2980cb5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
